# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9aa1764fd568c13a50a84217de45ad32895622c714e8ec8de3cbe7e5528f8e2695234e23e1e4e2772c40c7f39ae22234294b81c831b5b8e2b8b66b9db307632f

test:
  secret_key_base: 6ee3007785f70a57f2a93db8d4d4cb5e5f9a14fd66327a2001f15a134d3e2d324f9521fe31471b1e284b54b8e3f6e7ceadf9f135886023005a532519600ada3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
